# Generated by Django 5.0.6 on 2024-06-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_content_en_article_content_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_fr',
        ),
    ]
